### ISSUE TITLE
Can't open app

### ISSUE THREAD

**Issue by arichua** [jmir1/aniyomi#323]
### Steps to reproduce

Same with latest tachiyomi, already installed the app but when i tried opening it, it keeps closing..

### Expected behavior

Should be able to open the app

### Actual behavior

Keep closing.

### Crash logs

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: Could not create Crashlytics-specific directory: /mnt/expand/ebccd6e4-582b-4832-9d88-ff1f11d0a0c3/user/0/xyz.jmir.tachiyomi.mi.debug/files/.com.google.firebase.crashlytics.files.v1
	at android.app.ActivityThread.installProvider(ActivityThread.java:7659)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7133)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7006)
	at android.app.ActivityThread.access$1500(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1990)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8087)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.IllegalStateException: Could not create Crashlytics-specific directory: /mnt/expand/ebccd6e4-582b-4832-9d88-ff1f11d0a0c3/user/0/xyz.jmir.tachiyomi.mi.debug/files/.com.google.firebase.crashlytics.files.v1
	at com.google.firebase.crashlytics.internal.persistence.FileStore.prepareBaseDir(FileStore.java:10)
	at com.google.firebase.crashlytics.internal.persistence.FileStore.<init>(FileStore.java:2)
	at com.google.firebase.components.Component$$ExternalSyntheticLambda0.create(Unknown Source:14)
	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda0.get(Unknown Source:3)
	at com.google.firebase.components.Lazy.get(Lazy.java:5)
	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:5)
	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:24)
	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:28)
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:9)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2386)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:3)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7654)
	... 10 more

### Aniyomi version

0.12.3.6-4504

### Android version

11

### Device

Redmi 9T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by sarinregmi** [comment]
@arichua did you figure out what the issue was.
I am seeing a similar issue, but to me looks more like a Crashlytics bug. It started happening after updating Firebase Crashlytics from 18.2.3 to 18.2.5. Something changed in 18.2.5 to cause this issue, works fine with 18.2.4.
Also this specific crash happens in the Xiaomi device only. 

On other devices I do not see crashes but just logs saying, 

```
[21526][FirebaseCrashlytics] Could not open log file: /data/user/0/com.mypackage/files/.com.google.firebase.crashlytics.files.v1/open-sessions/620ACB7B02A7000153A0113DF54A8709/userlog
    java.io.FileNotFoundException: /data/user/0/com.mypackage/files/.com.google.firebase.crashlytics.files.v1/open-sessions/620ACB7B02A7000153A0113DF54A8709/userlog.tmp: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:575)
```

**Comment by arichua** [comment]
Yes thank you. Actually it's not just Aniyomi but it happened too with other apps  i think it's because of the update of Xiaomi phone😅 my phone stopped working so i did a factory reset. Then i tried again installing Aniyomi and fortunately i am able to installed it.
